name: BbangMap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy deployment
        uses: appleboy/ssh-action@master
        with:
          script: |
            sudo git config --global --add safe.directory ~/BBang-map-test
            cd BBang-map-test
            sudo git checkout .
            sudo git pull origin main
            sudo npm install
            pm2 restart bbang-map-server
